CREATE TABLE [road_name_address] (
	[law_dong_cd] VARCHAR(10) NOT NULL,
	[sd_nm] VARCHAR(40) NOT NULL,
	[sgg_nm] VARCHAR(40),
	[law_umd_nm] VARCHAR(40),
	[law_li_nm] VARCHAR(40),
	[mt_yn] CHAR(1),
	[lot_ori_num] NUMERIC(4, 0) NOT NULL,
	[lot_sec_num] NUMERIC(4, 0) NOT NULL,
	[road_cd] VARCHAR(12) NOT NULL,
	[road_nm] VARCHAR(80),
	[base_yn] CHAR(1),
	[building_ori_cd] NUMERIC(5, 0),
	[building_sec_cd] NUMERIC(5, 0),
	[building_nm] VARCHAR(40),
	[building_dt_nm] VARCHAR(100),
	[building_mng_cd] VARCHAR(25) NOT NULL PRIMARY KEY,
	[umd_cd] VARCHAR(2),
	[adm_dong_cd] VARCHAR(10),
	[adm_dong_nm] VARCHAR(20),
	[post_cd] VARCHAR(5) NOT NULL,
	[post_seq] VARCHAR(3),
	[large_deli] VARCHAR(40),
	[deli_cd] VARCHAR(2),
	[mod_dt] VARCHAR(8),
	[pre_road_addr] VARCHAR(25),
	[sgg_buinding_nm] VARCHAR(200),
	[apt_yn] CHAR(1),
	[base_zon_num] VARCHAR(5),
	[detail_addr_yn] CHAR(1),
	[note1] VARCHAR(15),
	[note2] VARCHAR(15)
);